### PR TITLE
Nested fields flattened into an object and test cases

### PR DESCRIPTION
**Pull request by ferh6t**
Related Issue(s)
Related to issue #114

Added small function for nested objects for json logs. Test cases also includes an example for nested object.

### CODE REVIEW

**Comment by aybabtme** [comment]
thanks @ferh6t ☺️ do you mind fixing the failing tests?

**Comment by ferh6t** [comment]
Hi  @aybabtme,
For the TimeFields, MessageFields, and LevelFields, should we include support for nested field analysis? For instance, the configuration file could specify fields like "body.message" for message fields. I’ve made a small improvement—would you like me to include it as well?

**Comment by aybabtme** [comment]
@ferh6t I think this will work, but you'll need to rebase against the `master` branch to pick up the change to `golangci-lint`, similar to https://github.com/humanlogio/humanlog/pull/127#issuecomment-2480900552.

**Comment by aybabtme** [comment]
actually rerunning it made it pass. when merged to master, i'll run with the `--fast` flag so this is good to merge. thanks @ferh6t !

**Pull request merged**
